#!/bin/bash
# ============================================================================
# CID Bridge — Cloudflare Setup Script
# ============================================================================
# This script sets up Cloudflare Tunnel to expose your local cid-bridge
# securely over the internet via Cloudflare's edge network.
#
# Prerequisites:
#   1. A Cloudflare account (https://dash.cloudflare.com/sign-up)
#   2. A domain whose nameservers point to Cloudflare
#   3. cloudflared installed (already present: /usr/local/bin/cloudflared)
#   4. A built CID binary (already present: /root/cid/target/release/cid)
#
# Usage:
#   chmod +x setup-cloudflare.sh
#   ./setup-cloudflare.sh
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BRIDGE_DIR="$SCRIPT_DIR"
CLOUDFLARED_DIR="$HOME/.cloudflared"
CID_BINARY="/root/cid/target/release/cid"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║        CID Bridge — Cloudflare Setup                        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# --------------------------------------------------
# Step 0: Check prerequisites
# --------------------------------------------------
echo "[0/6] Checking prerequisites..."

if [ ! -f "$CID_BINARY" ]; then
    echo "  ⚠ CID binary not found at $CID_BINARY"
    echo "  → Build it first: cd /root/cid && make release"
    exit 1
fi
echo "  ✓ CID binary: $CID_BINARY ($(du -h "$CID_BINARY" | cut -f1))"

if ! command -v cloudflared &>/dev/null; then
    echo "  ⚠ cloudflared not found. Install it:"
    echo "    https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
    exit 1
fi
echo "  ✓ cloudflared: $(cloudflared --version)"

if ! command -v node &>/dev/null; then
    echo "  ⚠ node not found"
    exit 1
fi
echo "  ✓ node: $(node --version)"
echo ""

# --------------------------------------------------
# Step 1: Install bridge npm dependencies
# --------------------------------------------------
echo "[1/6] Installing cid-bridge npm dependencies..."
cd "$BRIDGE_DIR"
npm install --production
echo "  ✓ npm dependencies installed"
echo ""

# --------------------------------------------------
# Step 2: Authenticate cloudflared with Cloudflare
# --------------------------------------------------
echo "[2/6] Authenticating cloudflared with Cloudflare..."
echo ""
echo "  This will open a browser window. Log in to Cloudflare"
echo "  and authorize this server to create tunnels."
echo ""
echo "  If running headless (no browser), use the URL it prints"
echo "  to authenticate from another machine."
echo ""
read -rp "  Press Enter to continue (or Ctrl+C to skip this step)..."

if [ ! -f "$CLOUDFLARED_DIR/cert.pem" ]; then
    cloudflared tunnel login
    echo "  ✓ Authenticated with Cloudflare"
else
    echo "  → Already authenticated (cert.pem found)"
fi
echo ""

# --------------------------------------------------
# Step 3: Create the tunnel
# --------------------------------------------------
echo "[3/6] Creating Cloudflare Tunnel..."
TUNNEL_NAME="cid-bridge"

if ! cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
    cloudflared tunnel create "$TUNNEL_NAME"
    echo "  ✓ Tunnel '$TUNNEL_NAME' created"
else
    echo "  → Tunnel '$TUNNEL_NAME' already exists"
fi

# Show tunnel info
TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "$TUNNEL_NAME" | awk '{print $1}')
echo "  Tunnel ID: $TUNNEL_ID"
echo ""

# --------------------------------------------------
# Step 4: Configure the tunnel
# --------------------------------------------------
echo "[4/6] Configuring tunnel..."

cat > "$CLOUDFLARED_DIR/config.yml" << TUNNELCFG
# Cloudflare Tunnel configuration for cid-bridge
# Auto-generated by setup-cloudflare.sh

tunnel: $TUNNEL_NAME
credentials-file: $CLOUDFLARED_DIR/$TUNNEL_ID.json

ingress:
  # Route traffic to cid-bridge
  - hostname: $TUNNEL_NAME.yourdomain.com
    service: http://localhost:3000
  # Catch-all: 404
  - service: http_status:404
TUNNELCFG

echo "  ✓ Tunnel config written to $CLOUDFLARED_DIR/config.yml"
echo "  ⚠ IMPORTANT: Edit the hostname in the config above!"
echo "    Replace 'yourdomain.com' with your actual domain."
echo "    Then run: cloudflared tunnel route dns $TUNNEL_NAME your-subdomain.yourdomain.com"
echo ""

# --------------------------------------------------
# Step 5: Set up systemd services
# --------------------------------------------------
echo "[5/6] Setting up systemd services..."

# cid-bridge service
cp "$BRIDGE_DIR/config/cid-bridge.service" /etc/systemd/system/cid-bridge.service 2>/dev/null || cat > /etc/systemd/system/cid-bridge.service << 'SERVICEBRIDGE'
[Unit]
Description=CID Bridge — universal MCP bridge for AI chatbots
Documentation=https://codeberg.org/NutypeBuddha/cid-bridge
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/cid-bridge
ExecStart=/usr/bin/node /root/cid-bridge/src/index.js
Environment=CID_BINARY=/root/cid/target/release/cid
Environment=PORT=3000
Environment=NODE_ENV=production
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
SERVICEBRIDGE

# cloudflared tunnel service
cat > /etc/systemd/system/cloudflared-tunnel.service << 'SERVICETUNNEL'
[Unit]
Description=Cloudflare Tunnel for cid-bridge
Documentation=https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/
After=network.target
Wants=cid-bridge.service

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/cloudflared tunnel run cid-bridge
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
SERVICETUNNEL

systemctl daemon-reload
echo "  ✓ systemd services created"
echo ""

# --------------------------------------------------
# Step 6: Start services
# --------------------------------------------------
echo "[6/6] Starting services..."

systemctl enable cid-bridge.service
systemctl start cid-bridge.service
echo "  ✓ cid-bridge.service started (port 3000)"

systemctl enable cloudflared-tunnel.service
systemctl start cloudflared-tunnel.service
echo "  ✓ cloudflared-tunnel.service started"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Setup Complete!                                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Check status:"
echo "    systemctl status cid-bridge.service"
echo "    systemctl status cloudflared-tunnel.service"
echo ""
echo "  View logs:"
echo "    journalctl -u cid-bridge.service -f"
echo "    journalctl -u cloudflared-tunnel.service -f"
echo ""
echo "  Test locally:"
echo "    curl -s http://localhost:3000/health"
echo ""
echo "  Test via Cloudflare (after DNS is set):"
echo '    curl -s https://cid-bridge.yourdomain.com/health'
echo ""
echo "  Set an API key for security:"
echo "    Edit /root/cid-bridge/.env and set CID_BRIDGE_KEY"
echo "    Then restart: systemctl restart cid-bridge.service"
echo ""
echo "  Next steps:"
echo "  1. Edit /root/.cloudflared/config.yml — set your real domain"
echo "  2. Route DNS: cloudflared tunnel route dns cid-bridge your-subdomain.yourdomain.com"
echo "  3. Restart tunnel: systemctl restart cloudflared-tunnel.service"
echo "  4. Verify: curl https://your-subdomain.yourdomain.com/health"
echo ""
